Fix rounding issue in revaluation form.
City-of-Helsinki/att-sales-ui pull request #120
Opened 2024-09-13 12:39 UTC by rbreve

The rounding is not ceil rounding, it is rounded to the nearest number. IE if the value is 10.556 it will round to 10.56 if its 10.554 to 10.55

2024-09-13 12:43 UTC, rbreve commented
<img width="529" alt="Screenshot 2024-09-13 at 15 43 05" src="https://github.com/user-attachments/assets/2bf5f1bb-b4e7-4bb3-a9f9-4b9a4f8de1bd">
<img width="564" alt="Screenshot 2024-09-13 at 15 43 49" src="https://github.com/user-attachments/assets/d829dcf3-cdaa-4381-9922-b58291654212">

2024-09-16 12:16 UTC, voneiden requested changes

2024-09-16 13:05 UTC, rbreve commented on src/components/revaluation/ApartmentRevaluationForm.tsx
> +    const adjustedCostRounded = adjustedCost.toFixed(2);
that would fail too sometimes:

`value = 1.005
1.005
(Math.round(value * 100) / 100).toFixed(2);
'1.00'`

2024-09-17 12:42 UTC, voneiden approved these changes
Lessons learned :exploding_head: 

```
LGTM
GG
T T
M  M 
```

2024-09-17 12:54 UTC, merged