Initial apartment list on the project detail page
City-of-Helsinki/att-sales-ui pull request #7
Opened 2021-11-29 13:28 UTC by juhakujala

![localhost_3000_](https://user-images.githubusercontent.com/7901266/143876086-f978e215-7274-465a-8a7c-540af8bd2863.png)

2021-11-29 19:06 UTC, frwickst requested changes
Some small changes that  could help with maintainability :) Overall this looks good 👍

2021-11-29 19:06 UTC, frwickst commented on src/components/apartment/SortApartments.tsx
> +    if (sortConfig !== null) {
To save some indentation here, you could end early if `sortConfig === null` (or use the isEmpty mentioned earlier).
That way you can de-indent everything one step and just do `if (sortConfig === null) { return sortedApartments }.

2021-11-29 19:06 UTC, frwickst commented on src/components/apartment/SortApartments.tsx
> +        });
I would recommend splitting this out into its own function to ease readability a bit.

2021-11-29 19:06 UTC, frwickst commented on src/components/apartment/SortApartments.tsx
> +        });
I would recommend splitting this out into its own function to ease readability a bit.

2021-11-30 07:54 UTC, juhakujala commented on src/i18n/i18n.ts
> +  return stored !== null && stored !== undefined ? JSON.parse(stored) : 'fi';
I'll create a small util function out of this. I guess this will be used in many places after all.

2021-11-30 08:15 UTC, juhakujala commented on src/i18n/i18n.ts
> +  return stored !== null && stored !== undefined ? JSON.parse(stored) : 'fi';
`JSON.parse()` still complains that the value can be a string or null. So I'll leave it now as it is.

2021-11-30 14:43 UTC, frwickst approved these changes
LGTM 🚢  Good work!

2021-12-01 06:36 UTC, merged